spring.application.name=hilife

spring.datasource.url=jdbc:postgresql://localhost:5432/hilife
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=mysupersecurejwtsecretkeymysupersecurejwtsecretkey123

aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketName=hilife-images-vaishnavi