spring.application.name=hilife

spring.datasource.url=jdbc:postgresql://localhost:5432/hilife
spring.datasource.username=postgres
spring.datasource.password=Nagesh1234@

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=mysupersecurejwtsecretkeymysupersecurejwtsecretkey123
